### PR TITLE
percywtc/personal-timetable

### PR DESCRIPTION
**Pull request by percywtc**
Added zoom in/out transition while adding/removing courses to/from the timetable

### CODE REVIEW

**Comment by percywtc** [comment]
> Is it normal that when there are two courses in same cell, there is no zoom in effect?

Yes (currently, at least), there are two reasons for that:
- I haven't come up with a consistent mechanism to make a transition for more than one course. For example: from {courseA} to {courseA, courseB}, should I have the courseB with transition? Or should there be the box showing courseA, covered by a transitioning box that shows courseA and courseB?
- Implementation difficulty: currently the transition is made by adding a Container inside each of the table cells, and the Container is the one with transition effect. In other words, it's hard to place two Containers overlapping each other, with the previous courses in the back, and the new course in the fron with transition effect. Do you guys have any idea how to implement it?

> Besides, is it possible to add color to cell that has multiple courses?

What would the coloring mechnaism be if a cell of different courses have to be colorized? Also, I could actually colorize cells containing multiple "courses" with the same course, e.g. {CSCI3100T01, CSCI3100T02, CSCI3100}, if you guys agree that this is a better/more consistent approach

> Also I am thinking is it necessary to add a limit for adding courses in the same time slot (actually what is the maximum number of courses possible in reality)

Theoretically, many many. In this branch, however, I fixed the cell's height and hide texts outside the cell. This is because, otherwise, when a cell has more courses which stretch the cell's height, the containers on the same row would not update their height to match, thus creating situations where the color of a cell is not filling up the entire cell.

**Comment by wongloklam456** [comment]
> I haven't come up with a consistent mechanism to make a transition for more than one course. For example: from {courseA} to {courseA, courseB}, should I have the courseB with transition? Or should there be the box showing courseA, covered by a transitioning box that shows courseA and courseB?

Can't think of any good mechanism for now, I think it's ok to leave it at the moment.

> Implementation difficulty: currently the transition is made by adding a Container inside each of the table cells, and the Container is the one with transition effect. In other words, it's hard to place two Containers overlapping each other, with the previous courses in the back, and the new course in the from with transition effect. Do you guys have any idea how to implement it?

No idea lol. We can fix this if we have time in the future but I think it is acceptable to leave it even in the final code.

> What would the coloring mechnaism be if a cell of different courses have to be colorized? Also, I could actually colorize cells containing multiple "courses" with the same course, e.g. {CSCI3100T01, CSCI3100T02, CSCI3100}, if you guys agree that this is a better/more consistent approach

Yes, I think it is better.

> In reality, I think students generally could not register any courses with time collision. In my understanding, they could ask for department's approval, but the situation should be rare. So I expect students registering 3+ courses within a time slot would be really really rare.

Based on the fact that CNT allows timetable with credits much larger than the limit in CUHK, I think we can just present this as an intentional feature haha

**Comment by percywtc** [comment]
@jeremy624 What do you think?

**Comment by percywtc** [comment]
@jeremy624 What do you think?

**Comment by jeremy624** [comment]
> I haven't come up with a consistent mechanism to make a transition for more than one course. For example: from {courseA} to {courseA, courseB}, should I have the courseB with transition? Or should there be the box showing courseA, covered by a transitioning box that shows courseA and courseB?
Implementation difficulty: currently the transition is made by adding a Container inside each of the table cells, and the Container is the one with transition effect. In other words, it's hard to place two Containers overlapping each other, with the previous courses in the back, and the new course in the fron with transition effect. Do you guys have any idea how to implement it?

I agree to leave it at the moment.

> What would the coloring mechnaism be if a cell of different courses have to be colorized? Also, I could actually colorize cells containing multiple "courses" with the same course, e.g. {CSCI3100T01, CSCI3100T02, CSCI3100}, if you guys agree that this is a better/more consistent approach

I think we should have some color for the cell with multiple courses, user may miss it as it looks similar to the cell with no course.
Perhaps we can have a list inside the tableCell and have different colors for different courses?
Not sure if it possible or will look good.

> In reality, I think students generally could not register any courses with time collision. In my understanding, they could ask for department's approval, but the situation should be rare. So I expect students registering 3+ courses within a time slot would be really really rare.

I think CUNT is a timetable planner but not a real timetable(?), so maybe we should allow to register courses with time collision for planning reason.
But I agree that we should set some limits as if there are too many courses in the same cell, the ui will looks bad.

Anyways I think you can merge it first and see if we have any ideas on it in the future.

**Comment by percywtc** [comment]
Let's work on desinging a colorizing mechanism soon!

**Pull request merged**
