### PR TITLE
Implemented getAllUsers() API. Created User List in mastertimetable.js

### PR DESCRIPTION
**Pull request by jeremy624**
Implemented getAllUsers() API. Created User List in mastertimetable.js

### CODE REVIEW

**Comment by ianwong1999** [comment]
btw do we need to limit the maximum no. of ppl chosen in mastertimetable

**Comment by percywtc** [comment]
> btw do we need to limit the maximum no. of ppl chosen in mastertimetable

I think so

**Comment by percywtc** [comment]
BTW, the avatar will be changed to images after adding its support right?

**Comment by jeremy624** [comment]
> BTW, the avatar will be changed to images after adding its support right?

Yea. Maybe just show this icon when user didn't set any avatar.

**Comment by percywtc** [comment]
LGTM! I think you can merge :)

**Pull request merged**
